name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build with Buildozer
      uses: artem-sobolev/buildozer-action@v1
      with:
        buildozer_version: stable
        
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-apk
        path: bin/*.apk
